
# Path to top level ASF directory relative to this project directory.
PRJ_PATH = # set to asf toplevel path

# Microcontroller: atxmega128a1, atmega128, attiny261, etc.
MCU = atxmega192a3u

# Application target name. Given with suffix .a for library and .elf for a
# standalone application.
TARGET = crypto.elf
